version: "3"
services:
  postgres:
    image: "postgres"
    container_name: "postgres"
    environment:
      - POSTGRES_USER=john
      - POSTGRES_PASSWORD=shhhht
      - POSTGRES_DB=project
    ports:
      - 5432:5432
